# Generated by Django 5.1.7 on 2025-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_treinamento', models.IntegerField()),
                ('treinamento', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=100)),
                ('proposta', models.CharField(max_length=120)),
                ('empresa', models.CharField(max_length=120)),
                ('cliente', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ANDAMENTO', 'Em andamento'), ('CONCLUÍDO', 'Conclúido')], default='ANDAMENTO', max_length=15)),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('dias_treinamento', models.IntegerField()),
                ('turno', models.CharField(max_length=15)),
                ('horas', models.DateTimeField()),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
    ]
