# Generated by Django 5.1.7 on 2025-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosgerais',
            name='status',
            field=models.CharField(choices=[('ANDAMENTO', 'Em andamento'), ('CONCLUÍDO', 'Concluído')], default='ANDAMENTO', max_length=15),
        ),
    ]
