# Generated by Django 5.1.7 on 2025-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_dadosgerais_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosgerais',
            name='horas',
            field=models.TimeField(),
        ),
    ]
