# Generated by Django 5.1.7 on 2025-03-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_dadosgerais_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('regiao', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('formacao', models.TimeField()),
                ('modalidade', models.CharField(choices=[('EAD', 'EAD'), ('PRESENCIAL', 'Presencial')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='dadosgerais',
            name='codigo_treinamento',
        ),
        migrations.AlterField(
            model_name='dadosgerais',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_gerais', to='agendamentos.cliente'),
        ),
        migrations.AlterField(
            model_name='dadosgerais',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_gerais', to='agendamentos.docente'),
        ),
        migrations.AlterField(
            model_name='dadosgerais',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_gerais', to='agendamentos.treinamento'),
        ),
    ]
