# Generated by Django 5.1.7 on 2025-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_cliente_docente_treinamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='formacao',
            field=models.IntegerField(),
        ),
    ]
